app:
  name: 
  run_mode: 
  addr: 
  port: 
  jwt_expiration_time: 
  rsa_private_key_path: 
  rsa_public_key_path: 
  log_output_dir: 
minio:
  endpoint: 
  access_key_id: 
  secret_access_key: 
  use_ssl: false
  bucket_names:
    - "moity-blog"
  location: "cn-east-1"
database: 
  postgres:
    host: 
    port: 
    username: 
    password: 
    db_name: 
    sslmode: "disable"
    auto_create_db: false
  gorm:
    log_level: "ERROR"
    log_output_dir: 
kafka:
  brokers:
    - 
  version: "4.0.0"
  client_id: "blog-server"
  producer:
    retry_max: 
    retry_backoff: 
    required_acks: "all"
    timeout: 
    compression: "snappy"
  consumer:
    group_id: "blog-server-group"
    auto_offset_reset: "latest"
    session_timeout: 
    heartbeat_interval: 
    rebalance_timeout: 
  tls:
    enable: false
    ca_file: "temp/ca.pem"
    cert_file: "temp/client-cert.pem"
    key_file: "temp/client-key.pem"
    skip_verify: false
redis:
  addr: 
  password: 
  db: 
  dial_timeout: 
  read_timeout: 
  write_timeout: 
  pool_size: 
  key_prefix: 
email:
  smtp_host: 
  smtp_port: 
  smtp_username: 
  smtp_password: 
  sender_name: 
  sender_email: 
  email_template:
