app:
  name: "MOITY Blog Backend"
  run_mode: "local"
  addr: "127.0.0.1"
  port: ":8080"
  jwt_secret: "123456"
  # 7 days
  jwt_expiration_time: 7
minio:
  endpoint: "10.21.23.14:10004"
  access_key_id: "cxb944fJZaWvdZrnhB3V"
  secret_access_key: "mZUASbUjdRXO4zoKnAfmZbbVihPgt7gljPAZ1PrH"
  use_ssl: false
  bucket_names:
    - "moity-blog"
  locaiton: "cn-east-1"
database: 
  postgres:
    host: "10.21.23.14"
    port: "5432"
    username: "postgres"
    password: "10130420"
    db_name: "moity_blog"
    sslmode: "disable"
  gorm:
    log_level: "ERROR"
    log_output_dir: "./logs"